### ISSUE TITLE
problem specifying value_minimum and value_maximum in create_output_type_sample()

### ISSUE THREAD

**Issue by nickreich** [Infectious-Disease-Modeling-Hubs/hubUtils#130]
``` r
hubUtils::create_output_type_sample(
    required = 1:500,
    optional = NULL,
    value_type = "double",
    value_minimum = 0L,
    value_maximum = 1L
)
#> Error in `map()`:
#> ℹ In index: 2.
#> Caused by error in `hubUtils::create_output_type_sample()`:
#> ✖ Invalid schema. Cannot determine appropriate type for argument
#>   `value_minimum`. Please open an issue at
#>   <https://github.com/Infectious-Disease-Modeling-Hubs/schemas/issues>
#> Backtrace:
#>      ▆
#>   1. └─hubUtils::create_output_type_sample(...)
#>   2.   └─hubUtils:::create_output_type_dist(...)
#>   3.     └─purrr::walk(...)
#>   4.       └─purrr::map(.x, .f, ..., .progress = .progress)
#>   5.         └─purrr:::map_("list", .x, .f, ..., .progress = .progress)
#>   6.           ├─purrr:::with_indexed_errors(...)
#>   7.           │ └─base::withCallingHandlers(...)
#>   8.           ├─purrr:::call_with_cleanup(...)
#>   9.           └─hubUtils (local) .f(.x[[i]], ...)
#>  10.             └─hubUtils:::check_input(...)
#>  11.               └─cli::cli_abort(...)
#>  12.                 └─rlang::abort(...)
```

<sup>Created on 2024-01-03 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by nickreich** [comment]
The same things happens above if only value_maximum is specified.

**Comment by annakrystalli** [comment]
So I managed to track the source of this issue which does indeed lie in the schema. 

Specifically it relates to the still open issue regarding the `value` data types for samples which have not been definitively settled on: https://github.com/Infectious-Disease-Modeling-Hubs/schemas/issues/37
 (i.e. most likely to be numeric but also the potential for categorical has been discussed too.

As a result, there is nothing really to validate the `maximum` and `minimum` properties and this ends up in throwing an error, specifically when trying to detect/validate the data type of the minimum and maximum properties. 

What I've done is downgrade this to a warning rather than an error and skip `minimum` and `maximum` type validation for now.

Hopefully, given we'll be working on samples (including the schema for samples) we'll resolve the open schema issue at the same time.
