### ISSUE TITLE
[Input validation - LOAD] Scenario #2 Invalid task_id filtering value

### ISSUE THREAD

**Issue by annakrystalli** [Infectious-Disease-Modeling-Hubs/hubUtils#17]
In this scenario, the user requests data using an invlaid filtering value for a task_id. There are again two scenarios where this could happen

## Incorrectly input task_id filtering value

Part of these checks is to ensure task_id filters are implemented correctly. A user might request specific values of a task_id but there might be a typo. e.g. requesting `location = USA`  instead of `location = US`

### Options for action

- [ ] Throw an error and direct user to the invalid task id filtering value
- [ ] Throw a warning. ignore invalid task id filtering value and return data matching all other valid filters (could make the returned data significantly larger?)

### task_id filtering value not available in one or more rounds but available in others

Let's assume that task id `age_group` valid targets included `["0-5", "6-18", "19-24", "25-64", "65+"]` in `round-1` of a hub but in  `round-2` and thereafter it became more fine grained e.g. `["0-5", "6-18", "19-24", "25-34", "35-44", "45-54", "55-64", "65+"]`. A user requests data from `round-1` and `round-2` and includes an age group filter, let's say `35-44`. What do we want the behaviour of input validation checks to be?

### Options for action

- [ ] Throw an error (I think no but including for completeness)
- [ ] Throw a warning about `35-44` not being a valid filtering value for `age_group` in `round-1` and return ALL data from `round-1` 
- [ ] Throw a warning about `35-44` not being a valid filtering value for `age_group` in `round-1` and return NO data from `round-1` 
- [ ] Throw a warning and control whether ALL or NO data for rounds where the task_id is invalid through an argument.

## Distinguishing between the two situations

Again, we may want different behaviour between the two aforementioned situations. For example if we want an error in the first situation and a warning in the second, we need to be able to distinguish between the two. One option could be that if a given task_id filtering value is not found in any rounds, assume we are dealing with the first situation otherwise assume we are dealing with situation 2.

**Comment by elray1** [comment]
I vote for:
 - For first "Options for action", throw an error
 - For second "Options for action", option 3 or 4. I think I prefer option three (throw a warning and return no data), but could be convinced otherwise.
 
And I agree with your criterion for distinguishing between the situations: if I collect all the unique values that exist in the metadata config file for `task_id`s named `age_group`, and the user has specified a value that is not in any of those, we throw a warning.

One more consideration here: maybe we should provide an argument that allows the user to say they don't want warnings to be issued.  Continuing the running example, suppose a user is aware of the different age groupings that were used in the two rounds, but they still want all the data related to age groups covering people between 25 and 64. They might specify arguments like `round = c("round-1", "round-2"), age_group = c("25-64", "25-34", "35-44", "45-54", "55-64")` with full knowledge that this will result in different sets of data for the two rounds. It would be nice if the user could do this without generating warnings.
