### ISSUE TITLE
Error message not clear with hubUtils::validate_config

### ISSUE THREAD

**Issue by LucieContamin** [Infectious-Disease-Modeling-Hubs/hubUtils#41]
I was trying to validate the config files in the [megaround-scenariohub](https://github.com/midas-network/megaround-scenariohub/) repository and I got an error but the message is confusing. 

I first got an `Error in loadNamespace(x) : there is no package called ‘jsonvalidate’` error that I easily fixed by installing jsonvalidate but it might be good to change the DESCRIPTION file to have it on import instead of suggest.

The second error I have, I am not certain how to fix it: 
```
> hubUtils::validate_config(hub_path = ".")
Error in `purrr::map_chr()` at hubUtils/R/validate-config-file.R:275:2:
ℹ In index: 1.
Caused by error in `rep()`:
! invalid 'times' argument
Run `rlang::last_error()` to see where the error occurred.
Warning message:
Schema errors detected in config file ./hub-config/tasks.json validated against schema <https://raw.githubusercontent.com/Infectious-Disease-Modeling-Hubs/schemas/main/v0.0.0.9/tasks-schema.json> 

> rlang::last_error()
<error/purrr_error_indexed>
Error in `purrr::map_chr()` at hubUtils/R/validate-config-file.R:275:2:
ℹ In index: 1.
Caused by error in `rep()`:
! invalid 'times' argument
---
Backtrace:
  1. hubUtils::validate_config(hub_path = ".")
  3. hubUtils::launch_pretty_errors_report(validation)
       at hubUtils/R/validate-config-file.R:105:6
  4. purrr::map_chr(error_df[["instancePath"]], path_to_tree)
       at hubUtils/R/validate-config-file.R:275:2
  5. purrr:::map_("character", .x, .f, ..., .progress = .progress)
  9. hubUtils (local) .f(.x[[i]], ...)
 11. base::paste(rep("─", times = i - 2), collapse = "")
       at hubUtils/R/validate-config-file.R:381:4
Run `rlang::last_trace()` to see the full context.

```
It seems to be link to the "schema_version" parameter that has a length of 1, if I understand correctly. But, I am not sure how to fix it.

**Comment by annakrystalli** [comment]
Hey @LucieContamin 

Thanks for the bug report!

The first error is because we are using the `Suggests` to list packages that hub maintainers might need but users that just want to load data don't. This is because the `V8` package that `jsonvalidate` depends on can be annoying to install on Linux but is only required for the schema validation so we didn't want to require it for all users.

There's a note about it at the top of the vignette https://infectious-disease-modeling-hubs.github.io/hubUtils/articles/hub-setup.html but I knew that wasn't enough so I've added a check for it in the function. Now if the `jsonvalidate` isn't installed when you call `validate_config()` you get a more informative message with instructions.

I've pushed this change as well as the dynamic validation functionality to branch `r-config-val` (still need to write more tests before it can be reviewed and merged). 

You can install it with:
```r
remotes::install_github("Infectious-Disease-Modeling-Hubs/hubUtils", ref = "r-config-val", dependencies = TRUE)
```

#### Use `v0.0.1` schema

The latest schema version was (unreleased) on the `v0.0.1` branch in the schemas repo but I've just gone ahead and released it on the `main` branch for you. 

Now if I run (in the megaround project):
```r
library(hubUtils)
validate_config(config = "tasks")
```
I get:
```
Error in `get_config_schema_version()`:
! Valid version could not be extracted from config file
  ./hub-config/tasks.json
! Please check property "schema_version" is correct.
```
because there is no `schema_version` property. This is necessary for validation to be performed correctly. (see https://github.com/Infectious-Disease-Modeling-Hubs/schemas/blob/c71c4e655dbf2cd293176d5cf421a3782aa13c66/v0.0.1/tasks-schema.json#L8-L12)


When I add:
```json
"schema_version": "https://github.com/Infectious-Disease-Modeling-Hubs/schemas/blob/main/v0.0.1/tasks-schema.json",
```
above the `rounds` property in your `tasks.json`, I now get a single error relating to the fact you are using `output_types` rather than `output_type`. 

Once I fix that, validation succeeds!!

Note that I've removed the automatic launching of a more user friendly error report. That now is in a separate function called `view_config_val_errors()`. However the bug is somewhere in that function (which was triggered automatically in the previous version of hubUtils) so I will use your `tasks.json` to figure out why it's causing `view_config_val_errors()` to fail.

You can still access the errors table generated by `jsonvalidate` package with:
```r
out <- validate_config(config = "tasks")
attr(out, "errors")
```

**Comment by LucieContamin** [comment]
Hey @annakrystalli ,

Thank you very much for the detailed information. It makes more sense now. 

For the install, I did not consult the vignette when I install the package I just look at the README, so might be interesting to add that information on the README too. 

I will update the schema version and fix my output-type errors! 

Thank you very much again

**Comment by annakrystalli** [comment]
Yes you're totally right about the `README`. It definitely needs to be mentioned there.
